name: safeway
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "2.22.0"
  firebase_auth: "4.14.0"
  provider: "6.1.1"
  firebase_core_platform_interface: 5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

assets:
  - assets/

flutter:
  uses-material-design: true

